spring:
  profiles:
    active:prod

---

spring:
  profiles: dev
  application:
    name: garagespace-app-service
	
feign:
  hystrix:
    enabled: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka.chekugongzuoshi.com:6001/eureka/,http://eureka.chekugongzuoshi.com:6002/eureka/,http://eureka.chekugongzuoshi.com:6003/eureka/
  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: garagespace-app
  company.name: www.garagespace.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

apache:
  rocketmq:
    consumer:
      PushConsumer: from-back-producer
    namesrvAddr: 47.107.236.151:9876
---

spring:
  profiles: prod
  application:
    name: garagespace-app-service
 
feign:
  hystrix:
    enabled: true


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka.chekugongzuoshi.com:6001/eureka/,http://eureka.chekugongzuoshi.com:6002/eureka/,http://eureka.chekugongzuoshi.com:6003/eureka/
  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: garagespace-app
  company.name: www.garagespace.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

apache:
  rocketmq:
    consumer:
      PushConsumer: from-back-producer
    namesrvAddr: 47.107.236.151:9876




