spring:
  profiles:
    active: prod
---
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    prefer-ip-address: true

spring:
  profiles: dev
  redis:
    host: 47.107.236.151
    password: abc123ABC
zookeeper:
  addr: 106.13.39.248:32181
  timeout: 5000
gs:
  rocketmq:
    accessKey: LTAISk9ljIMoAwg4
    secretKey: toWpFJorcB8j86AkoBK0NQDCj4NOWm
    # namesrvAddr地址
    namesrvAddr: http://MQ_INST_1518141642160924_BanExLH4.mq-internet-access.mq-internet.aliyuncs.com:80  #47.107.236.151:9876
    # 事务生产者group名称(服务dynamic)
    dynamicGroupName: GID_Dynamic_App_Group_Name_Dev
    # 一次最大消费多少数量消息
    consumerBatchMaxSize: 1
    # 广播消费
    consumerBroadcasting: false
    # 启动的时候是否消费历史记录
    enableHisConsumer: false
    # 启动顺序消费
    enableOrderConsumer: false

# Elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
elasticsearch:
  ip: 114.115.165.69
  port: 9300
  pool: 5
#注意cluster.name需要与config/elasticsearch.yml中的cluster.name一致
  cluster:
   name: elasticsearch
---
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://182.61.57.172:30601/eureka/,http://182.61.57.172:30602/eureka/
  instance:
    prefer-ip-address: true

spring:
  profiles: prod
  redis:
    host: 47.107.236.151
    password: abc123ABC
zookeeper:
  addr: 106.13.39.248:32181
  timeout: 5000
gs:
  rocketmq:
    accessKey: LTAISk9ljIMoAwg4
    secretKey: toWpFJorcB8j86AkoBK0NQDCj4NOWm
    # namesrvAddr地址
    namesrvAddr: http://MQ_INST_1518141642160924_BanExLH4.mq-internet-access.mq-internet.aliyuncs.com:80  #47.107.236.151:9876
    # 事务生产者group名称(服务dynamic)
    dynamicGroupName: GID_Dynamic_App_Group_Name_Prod
    # 一次最大消费多少数量消息
    consumerBatchMaxSize: 1
    # 广播消费
    consumerBroadcasting: false
    # 启动的时候是否消费历史记录
    enableHisConsumer: false
    # 启动顺序消费
    enableOrderConsumer: false

# Elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
elasticsearch:
  ip: 114.115.165.69
  port: 9300
  pool: 5
#注意cluster.name需要与config/elasticsearch.yml中的cluster.name一致
  cluster:
   name: elasticsearch